export const config = {
    password: '',
    username: 'grepug@163.com',
    nickname: 'grepugg',
    buildConfig: {
        appEnName: '',
        version: '',
        verCode: 1,
        verType: 1,
        platform: '0,1',
        engine: '',
        powers: '1,2,4',
        iosDevice: 1,
        isWatch: 0,
        security: 0,
        jsZip: 0,
        buildVersion: '0.0.1',
        tdSelect:
            'qihoo360;tencentApp;91Market;baiduApp;androidMarket;wandoujia;xiaomiMarket;anzhiMarket;appChina;huaweiAppstore;meizuAppstore;gfanAppstore',
        isTDChannel: 0,
        androidBetaEngine: 1,
        debug: '',
        remark: '',
        'ios_perm[NSCameraUsageDescription]': '',
        'ios_perm[NSMicrophoneUsageDescription]': '',
        'ios_perm[NSPhotoLibraryUsageDescription]': '读取图片',
        'ios_perm[NSContactsUsageDescription]': '',
        'ios_perm[NSLocationWhenInUseUsageDescription]': '',
        'ios_perm[NSLocationAlwaysUsageDescription]': '',
        'ios_perm[NSLocationAlwaysAndWhenInUseUsageDescription]': '',
        'ios_perm[NSBluetoothPeripheralUsageDescription]': '',
        'ios_perm[NSCalendarsUsageDescription]': '',
        'ios_perm[NSHealthShareUsageDescription]': '',
        'ios_perm[NSHealthUpdateUsageDescription]': '',
        'ios_perm[NSHomeKitUsageDescription]': '',
        'ios_perm[NSMotionUsageDescription]': '',
        'ios_perm[NSRemindersUsageDescription]': '',
        'ios_perm[NSSiriUsageDescription]': '',
        'ios_perm[NSSpeechRecognitionUsageDescription]': '',
        'ios_perm[NSAppleMusicUsageDescription]': '',
        'ios_perm[NSPhotoLibraryAddUsageDescription]': '添加照片',
        'ios_perm[NFCReaderUsageDescription]': '',
        'ios_perm[NSFaceIDUsageDescription]': '',
    },
};
